### PR TITLE
fix: fix log param error

### PR DESCRIPTION
**Pull request by Akagi201**

### CODE REVIEW

**Comment by oryband** [comment]
hey @Akagi201 . Thanks for the PR. Can you describe what are you attempting to fix here and in which scenario? We're not getting any build or test errors.

**Comment by Akagi201** [comment]
```
cd github.com/kinecosystem/go/support/log
go build
```

```
❯ go build
# github.com/kinecosystem/go/support/log
./entry.go:148:14: cannot use hook.Entries (type []logrus.Entry) as type []*logrus.Entry in return argument
```

**Comment by oryband** [comment]
I can't reproduce this on our Docker build environment:
```bash
$:/go/src/github.com/kinecosystem/go# cd support/log/
$:/go/src/github.com/kinecosystem/go/support/log# go build
# exits successfully
```
What OS, version, and other relevant environment settings are you using? Here's an example on how we set up the build envrionment in Docker:
```Dockerfile
FROM golang:1.11-stretch  # based on Debian

RUN BUILD_DEPS="build-essential git mercurial postgresql-client mysql-client"; \
    apt-get -qq update && apt-get -qq install $BUILD_DEPS

RUN curl -sS https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN mkdir -p /go/src/github.com/kinecosystem/go
WORKDIR "/go/src/github.com/kinecosystem/go"
VOLUME ["/go/src/github.com/kinecosystem/go"]
```

**Comment by oryband** [comment]
See here: https://github.com/kinecosystem/blockchain-ops/blob/179a12236d699d9e5ef77a2e69528596eb2fd6a4/images/dockerfiles/Dockerfile.horizon-build

**Comment by Akagi201** [comment]
I built it on macOS. go1.11.2

**Comment by oryband** [comment]
Do you install dependencies using the Go dep tool? Are you sure you're using the same pinned version for Logrus as defined in Gopkg.toml ?

**Comment by Akagi201** [comment]
I think maybe the library version is not the same.
I may use the newer log lib.

**Comment by oryband** [comment]
> I may use the newer log lib.

We're using vendored dependencies using the Go dep tool, this makes sure the dependencies' versions are stable.

**Comment by oryband** [comment]
Lemme know if the issue is resolved after trying the above. If all is well I'll close this issue.

**Comment by Akagi201** [comment]
My docker build also works. So close it.

**Pull request closed without merging**
